# Generated by Django 2.2 on 2019-04-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=100)),
                ('date_register', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expire', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('off', models.FloatField(default=0)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'shoe_categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('postalcode', models.CharField(max_length=11)),
                ('register_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_network', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pay', models.BooleanField(default=False)),
                ('post_refer', models.CharField(blank=True, max_length=35, null=True)),
                ('status', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('price_sell', models.FloatField()),
                ('price_buy', models.FloatField()),
                ('date_buy', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('number_buy', models.IntegerField()),
                ('number_left', models.IntegerField()),
                ('categories', models.ManyToManyField(to='Store.Category')),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.IntegerField()),
            ],
            options={
                'db_table': 'shoe_sizes',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticketText', models.TextField()),
                ('response_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_text', models.TextField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Customer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Store.Ticket')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Shoe')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Size')),
            ],
            options={
                'db_table': 'size_shoes',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('shoe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Shoe')),
            ],
            options={
                'db_table': 'shoe_pictures',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Ad')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Order')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Size')),
            ],
            options={
                'db_table': 'orderitems',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Payment'),
        ),
        migrations.CreateModel(
            name='AdSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Ad')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Size')),
            ],
            options={
                'db_table': 'size_ads',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='shoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.Shoe'),
        ),
    ]
