# Generated by Django 2.2 on 2019-04-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ad',
            table='shoe_ads',
        ),
    ]
